export const HEADER_HEIGHT = 64;
export const MAX_LIKES_CLICK_COUNT = 10;
export const keyboardData = [
  [
    { name: 'Esc', code: 'Escape' },
    { name: '1', code: 'Digit1' },
    { name: '2', code: 'Digit2' },
    { name: '3', code: 'Digit3' },
    { name: '4', code: 'Digit4' },
    { name: '5', code: 'Digit5' },
    { name: '6', code: 'Digit6' },
    { name: '7', code: 'Digit7' },
    { name: '8', code: 'Digit8' },
    { name: '9', code: 'Digit9' },
    { name: '0', code: 'Digit0' },
    { name: '-', code: 'Minus' },
    { name: '=', code: 'Equal' },
    { name: 'Backspace', code: 'Backspace', width: 2 },
    { name: 'Ins', code: 'Insert' },
  ],
  [
    { name: 'Tab', code: 'Tab', width: 1.5 },
    { name: 'ㅂ', code: 'KeyQ' },
    { name: 'ㅈ', code: 'KeyW' },
    { name: 'ㄷ', code: 'KeyE' },
    { name: 'ㄱ', code: 'KeyR' },
    { name: 'ㅅ', code: 'KeyT' },
    { name: 'ㅛ', code: 'KeyY' },
    { name: 'ㅕ', code: 'KeyU' },
    { name: 'ㅑ', code: 'KeyI' },
    { name: 'ㅐ', code: 'KeyO' },
    { name: 'ㅔ', code: 'KeyP' },
    { name: '[', code: 'BracketLeft' },
    { name: ']', code: 'BracketRight' },
    { name: '\\', code: 'Backslash', width: 1.5 },
    { name: 'Del', code: 'Delete' },
  ],
  [
    { name: 'CapsLock', width: 1.9, code: 'CapsLock' },
    { name: 'ㅁ', code: 'KeyA' },
    { name: 'ㄴ', code: 'KeyS' },
    { name: 'ㅇ', code: 'KeyD' },
    { name: 'ㄹ', code: 'KeyF' },
    { name: 'ㅎ', code: 'KeyG' },
    { name: 'ㅗ', code: 'KeyH' },
    { name: 'ㅓ', code: 'KeyJ' },
    { name: 'ㅏ', code: 'KeyK' },
    { name: 'ㅣ', code: 'KeyL' },
    { name: ';', code: 'Semicolon' },
    { name: "'", code: 'Quote' },
    { name: 'Enter', width: 2.1, code: 'Enter' },
    { name: 'PgUp', code: 'PageUp' },
  ],
  [
    { name: 'Shift', code: 'ShiftLeft', width: 2.1 },
    { name: 'ㅋ', code: 'KeyZ' },
    { name: 'ㅌ', code: 'keyX' },
    { name: 'ㅊ', code: 'keyC' },
    { name: 'ㅍ', code: 'keyV' },
    { name: 'ㅠ', code: 'keyB' },
    { name: 'ㅜ', code: 'keyN' },
    { name: 'ㅡ', code: 'keyM' },
    { name: ',', code: 'Comma' },
    { name: '.', code: 'Period' },
    { name: '/', code: 'Slash' },
    { name: 'Shift', code: 'ShiftRight', width: 1.9 },
    { name: '^', code: 'ArrowUp' },
    { name: 'PgDn', code: 'PageDown' },
  ],
  [
    { name: 'Ctrl', code: 'ControlLeft', width: 1.1 },
    { name: 'Win', code: 'MetaLeft', width: 1.1 },
    { name: 'Alt', code: 'AltLeft', width: 1.1 },
    { name: 'Space', code: 'Space', width: 6.7 },
    { name: 'Alt', code: 'AltRight' },
    { name: 'Win', code: 'MetaRight' },
    { name: 'Ctrl', code: 'ControlRight' },
    { name: '<', code: 'ArrowLeft' },
    { name: 'v', code: 'ArrowDown' },
    { name: '>', code: 'ArrowRight' },
  ],
];
export const MONITOR_DIMENSIONS = {
  width: 3,
  height: 1.6875,
  depth: 0.05,
  frameWidth: 0.1,
};
