export const HEADER_HEIGHT = 64;
export const MAX_LIKES_CLICK_COUNT = 10;
export const keyboardData = [
  [
    { name: 'Esc' },
    { name: '1' },
    { name: '2' },
    { name: '3' },
    { name: '4' },
    { name: '5' },
    { name: '6' },
    { name: '7' },
    { name: '8' },
    { name: '9' },
    { name: '0' },
    { name: '-' },
    { name: '=' },
    { name: 'Backspace', width: 2 },
    { name: 'Ins' },
  ],
  [
    { name: 'Tab', width: 1.5 },
    { name: 'ㅂ' },
    { name: 'ㅈ' },
    { name: 'ㄷ' },
    { name: 'ㄱ' },
    { name: 'ㅅ' },
    { name: 'ㅛ' },
    { name: 'ㅕ' },
    { name: 'ㅑ' },
    { name: 'ㅐ' },
    { name: 'ㅔ' },
    { name: '[' },
    { name: ']' },
    { name: '\\', width: 1.5 },
    { name: 'Del' },
  ],
  [
    { name: 'CapsLock', width: 1.9 },
    { name: 'ㅁ' },
    { name: 'ㄴ' },
    { name: 'ㅇ' },
    { name: 'ㄹ' },
    { name: 'ㅎ' },
    { name: 'ㅗ' },
    { name: 'ㅓ' },
    { name: 'ㅏ' },
    { name: 'ㅣ' },
    { name: ';' },
    { name: "'" },
    { name: 'Enter', width: 2.1 },
    { name: 'PgUp' },
  ],
  [
    { name: 'Shift', width: 2.1 },
    { name: 'ㅋ' },
    { name: 'ㅌ' },
    { name: 'ㅊ' },
    { name: 'ㅍ' },
    { name: 'ㅠ' },
    { name: 'ㅜ' },
    { name: 'ㅡ' },
    { name: ',' },
    { name: '.' },
    { name: '/' },
    { name: 'Shift', width: 1.9 },
    { name: '^' },
    { name: 'PgDn' },
  ],
  [
    { name: 'Ctrl', width: 1.1 },
    { name: 'Win', width: 1.1 },
    { name: 'Alt', width: 1.1 },
    { name: 'Space', width: 6.7 },
    { name: 'Alt' },
    { name: 'Win' },
    { name: 'Ctrl' },
    { name: '<' },
    { name: 'v' },
    { name: '>' },
  ],
];
